apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/kahaani/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 03 May 2026 21:30:13 IST
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/kahaani/.minikube/profiles/minikube/client.crt
    client-key: /home/kahaani/.minikube/profiles/minikube/client.key
