# ============================================================
# TaskFlow - Ansible Inventory
# Replace IP addresses with your actual EC2 public IPs
# (obtained from terraform output)
# ============================================================

[master]
taskflow-master ansible_host=43.205.232.130 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
taskflow-worker1 ansible_host=13.206.142.102 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
taskflow-worker2 ansible_host=3.109.32.254 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'